export enum CardType {
    EXPLODING_VOLTORB = 'Exploding Voltorb',
    DEFUSE = 'Defuse',
    ALTER_THE_FUTURE = 'Alter the future',
    SEE_THE_FUTURE = 'See the future',
    TARGETED_ATTACK = 'Targeted attack',
    ATTACK = 'Attack',
    DRAW_FROM_BOTTOM = 'Draw from bottom',
    FAVOR = 'Favor',
    SHUFFLE = 'Shuffle',
    SKIP = 'Skip',
    NOPE = 'Nope',
    BEARD_CAT = 'Cat card: beard cat',
    CATTERMELON_CAT = 'Cat card: cattermelon cat',
    POTATO_CAT = 'Cat card: potato cat',
    RAINBOW_CAT = 'Cat card: rainbow cat',
    TACO_CAT = 'Cat card: taco cat',
    FERAL_CAT = 'Feral cat',
};

// total 41
export const CardCountsSmall: Record<CardType, number> = {
    [CardType.EXPLODING_VOLTORB]: 0,
    [CardType.DEFUSE]: 0,
	[CardType.ALTER_THE_FUTURE]: 2,
    [CardType.SEE_THE_FUTURE]: 3,
    [CardType.TARGETED_ATTACK]: 2,
    [CardType.ATTACK]: 2,
    [CardType.DRAW_FROM_BOTTOM]: 3,
    [CardType.FAVOR]: 2,
    [CardType.SHUFFLE]: 2,
    [CardType.SKIP]: 4,
    [CardType.NOPE]: 4,
    [CardType.BEARD_CAT]: 3,
    [CardType.CATTERMELON_CAT]: 3,
    [CardType.POTATO_CAT]: 3,
    [CardType.RAINBOW_CAT]: 3,
    [CardType.TACO_CAT]: 3,
    [CardType.FERAL_CAT]: 2,
};

// total 60
export const CardCountsMedium: Record<CardType, number> = {
    [CardType.EXPLODING_VOLTORB]: 0,
    [CardType.DEFUSE]: 0,
	[CardType.ALTER_THE_FUTURE]: 4,
    [CardType.SEE_THE_FUTURE]: 3,
    [CardType.TARGETED_ATTACK]: 3,
    [CardType.ATTACK]: 3,
    [CardType.DRAW_FROM_BOTTOM]: 4,
    [CardType.FAVOR]: 4,
    [CardType.SHUFFLE]: 4,
    [CardType.SKIP]: 6,
    [CardType.NOPE]: 5,
    [CardType.BEARD_CAT]: 4,
    [CardType.CATTERMELON_CAT]: 4,
    [CardType.POTATO_CAT]: 4,
    [CardType.RAINBOW_CAT]: 4,
    [CardType.TACO_CAT]: 4,
    [CardType.FERAL_CAT]: 4,
};

// total 101
export const CardCountsLarge: Record<CardType, number> = {
    [CardType.EXPLODING_VOLTORB]: 0,
    [CardType.DEFUSE]: 0,
	[CardType.ALTER_THE_FUTURE]: 6,
    [CardType.SEE_THE_FUTURE]: 6,
    [CardType.TARGETED_ATTACK]: 5,
    [CardType.ATTACK]: 5,
    [CardType.DRAW_FROM_BOTTOM]: 7,
    [CardType.FAVOR]: 6,
    [CardType.SHUFFLE]: 6,
    [CardType.SKIP]: 10,
    [CardType.NOPE]: 9,
    [CardType.BEARD_CAT]: 7,
    [CardType.CATTERMELON_CAT]: 7,
    [CardType.POTATO_CAT]: 7,
    [CardType.RAINBOW_CAT]: 7,
    [CardType.TACO_CAT]: 7,
    [CardType.FERAL_CAT]: 6,
};